# application-admin.yml
app:
  root-path: /admin/pages/login.html

spring:
  config:
    import: aws-secretsmanager:/koreahistory/prod/rds

  datasource:
    url: jdbc:mysql://${host}:${port}/koreahistory?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=true&allowPublicKeyRetrieval=true
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  flyway:
    enabled: false   # ✅ Admin 서버는 DB 스키마 변경 없음

  sql:
    init:
      mode: never     # ✅ 초기 데이터 로드 금지 (data.sql 실행 안함)

  web:
    resources:
      static-locations: classpath:/static/admin/

  main:
    web-application-type: servlet

server:
  port: 8080