name: build-and-deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew clean bootJar

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: a-tti
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: a-tti
          path: .

      - name: Detect jar filename
        run: echo "JAR_NAME=$(ls *.jar | head -n 1)" >> $GITHUB_ENV

      - name: Setup SSH to Bastion
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BASTION_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secret.BASTION_HOST }}" >> ~/.ssh/known_hosts

      - name: Copy jar to Bastion
        run: |
          scp -i ~/.ssh/id_ed25519 "$JAR_NAME" ubuntu@${{ secrets.BASTION_HOST }}:/opt/deploy/a-tti/"$JAR_NAME"

      - name: Run deploy script on Bastion
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.BASTION_HOST }} \
            "cd /opt/deploy/a-tti && ./deploy.sh '$JAR_NAME'"
